import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['calendar'], operation: ['createSchedule'] };

export const createScheduleDescription: INodeProperties[] = [
	{
		displayName: '日程管理员',
		name: 'adminsCollection',
		type: 'fixedCollection',
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加管理员',
		typeOptions: { multipleValues: true },
		description: '日程的管理员userid列表，管理员必须在共享成员的列表中。最多指定3人',
		options: [
			{
				displayName: '管理员',
				name: 'admins',
				values: [
					{
						displayName: '成员UserID',
						name: 'userid',
						type: 'string',
						default: '',
						required: true,
						description: '管理员的UserID',
					},
				],
			},
		],
	},
	{
		displayName: '日程主题',
		name: 'summary',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: '日程主题，最长128字符',
		placeholder: '周例会',
	},
	{
		displayName: '开始时间',
		name: 'start_time',
		type: 'number',
		required: true,
		displayOptions: { show: showOnly },
		default: 0,
		description: '开始时间，秒级Unix时间戳',
	},
	{
		displayName: '结束时间',
		name: 'end_time',
		type: 'number',
		required: true,
		displayOptions: { show: showOnly },
		default: 0,
		description: '结束时间，秒级Unix时间戳',
	},
	{
		displayName: '参与者',
		name: 'attendeesCollection',
		type: 'fixedCollection',
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加参与者',
		typeOptions: { multipleValues: true },
		description: '日程参与者列表',
		options: [
			{
				displayName: '参与者',
				name: 'attendees',
				values: [
					{
						displayName: '成员UserID',
						name: 'userid',
						type: 'string',
						default: '',
						required: true,
						description: '参与者的UserID',
					},
				],
			},
		],
	},
	{
		displayName: '日程描述',
		name: 'description',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		typeOptions: { rows: 3 },
		description: '日程描述（可选）',
	},
	{
		displayName: '日程地点',
		name: 'location',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: '日程地点（可选）',
	},
	{
		displayName: '所属日历ID',
		name: 'cal_id',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: '所属日历ID（可选）',
	},
	{
		displayName: '应用ID',
		name: 'agentid',
		type: 'number',
		displayOptions: { show: showOnly },
		default: 0,
		description: '应用ID（可选），不填则使用当前应用',
		typeOptions: { minValue: 0 },
	},
];
