import type { INodeProperties } from 'n8n-workflow';
const showOnly = { resource: ['wedoc'], operation: ['addSmartsheetField'] };
export const addSmartsheetFieldDescription: INodeProperties[] = [
	{ displayName: '文档ID', name: 'docid', type: 'string', required: true, displayOptions: { show: showOnly }, default: '', description: '智能表格的docid' },
	{ displayName: '子表ID', name: 'sheet_id', type: 'string', required: true, displayOptions: { show: showOnly }, default: '', description: '子表的sheet_id' },
	{
		displayName: '字段列表',
		name: 'fieldsCollection',
		type: 'fixedCollection',
		required: true,
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加字段',
		typeOptions: { multipleValues: true },
		description: '要添加的字段列表',
		options: [
			{
				displayName: '字段',
				name: 'fields',
				values: [
					{
						displayName: '字段名称',
						name: 'field_title',
						type: 'string',
						default: '',
						required: true,
						description: '字段的显示名称',
					},
					{
						displayName: '字段类型',
						name: 'field_type',
						type: 'options',
						default: 'FIELD_TYPE_TEXT',
						required: true,
						options: [
							{ name: '文本', value: 'FIELD_TYPE_TEXT' },
							{ name: '数字', value: 'FIELD_TYPE_NUMBER' },
							{ name: '单选', value: 'FIELD_TYPE_SINGLE_SELECT' },
							{ name: '多选', value: 'FIELD_TYPE_MULTI_SELECT' },
							{ name: '日期', value: 'FIELD_TYPE_DATE' },
							{ name: '复选框', value: 'FIELD_TYPE_CHECKBOX' },
							{ name: '人员', value: 'FIELD_TYPE_USER' },
							{ name: '链接', value: 'FIELD_TYPE_URL' },
							{ name: '附件', value: 'FIELD_TYPE_ATTACHMENT' },
							{ name: '电话', value: 'FIELD_TYPE_PHONE' },
							{ name: '邮箱', value: 'FIELD_TYPE_EMAIL' },
							{ name: '地理位置', value: 'FIELD_TYPE_LOCATION' },
							{ name: '创建时间', value: 'FIELD_TYPE_CREATED_TIME' },
							{ name: '修改时间', value: 'FIELD_TYPE_MODIFIED_TIME' },
							{ name: '创建人', value: 'FIELD_TYPE_CREATED_USER' },
							{ name: '修改人', value: 'FIELD_TYPE_MODIFIED_USER' },
							{ name: '自动编号', value: 'FIELD_TYPE_AUTO_NUMBER' },
							{ name: '货币', value: 'FIELD_TYPE_CURRENCY' },
							{ name: '进度', value: 'FIELD_TYPE_PROGRESS' },
							{ name: '评分', value: 'FIELD_TYPE_RATING' },
							{ name: '公式', value: 'FIELD_TYPE_FORMULA' },
							{ name: '引用', value: 'FIELD_TYPE_REFERENCE' },
						],
						description: '字段的数据类型',
					},
					{
						displayName: '选项列表（单选/多选）',
						name: 'select_options',
						type: 'string',
						default: '',
						displayOptions: {
							show: {
								field_type: ['FIELD_TYPE_SINGLE_SELECT', 'FIELD_TYPE_MULTI_SELECT'],
							},
						},
						description: '选项列表，多个选项用英文逗号分隔',
						placeholder: '例如: 选项1,选项2,选项3',
					},
				],
			},
		],
	},
];
