import type { INodeProperties } from 'n8n-workflow';
const showOnly = { resource: ['wedoc'], operation: ['createForm'] };
export const createFormDescription: INodeProperties[] = [
	{
		displayName: '空间ID',
		name: 'spaceid',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: '空间spaceid',
		hint: '空间ID，可选',
	},
	{
		displayName: '父目录ID',
		name: 'fatherid',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: '父目录fileid, 在根目录时为空间spaceid',
		hint: '父目录ID，可选',
	},
	{
		displayName: '收集表标题',
		name: 'form_title',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: '收集表的标题',
		hint: '标题',
	},
	{
		displayName: '收集表描述',
		name: 'form_description',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: '收集表的描述说明',
		hint: '描述，可选',
	},
	{
		displayName: '表头背景图链接',
		name: 'form_header',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: '收集表表头背景图链接',
		hint: '图片URL，可选',
	},
	{
		displayName: '问题列表',
		name: 'questionList',
		type: 'fixedCollection',
		required: true,
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加问题',
		typeOptions: {
			multipleValues: true,
		},
		description: '收集表中的问题列表，最多200个问题',
		options: [
			{
				displayName: '问题',
				name: 'questions',
				values: [
					{
						displayName: '问题描述',
						name: 'question_title',
						type: 'string',
						default: '',
						required: true,
						description: '问题的标题',
					},
					{
						displayName: '问题类型',
						name: 'question_type',
						type: 'options',
						default: 1,
						options: [
							{ name: '文本', value: 1 },
							{ name: '单选', value: 2 },
							{ name: '多选', value: 3 },
							{ name: '位置', value: 5 },
							{ name: '图片', value: 9 },
							{ name: '文件', value: 10 },
							{ name: '日期', value: 11 },
							{ name: '时间', value: 14 },
							{ name: '下拉列表', value: 15 },
							{ name: '体温', value: 16 },
							{ name: '签名', value: 17 },
							{ name: '部门', value: 18 },
							{ name: '成员', value: 19 },
							{ name: '时长', value: 22 },
						],
						description: '问题的类型',
					},
					{
						displayName: '是否必答',
						name: 'is_required',
						type: 'boolean',
						default: false,
						description: '该问题是否必答',
					},
					{
						displayName: '问题备注',
						name: 'note',
						type: 'string',
						default: '',
						description: '问题的备注说明',
						hint: '可选',
					},
					{
						displayName: '编辑提示',
						name: 'placeholder',
						type: 'string',
						default: '',
						description: '输入框的提示文本',
						hint: '可选',
					},
					{
						displayName: '选项（单选/多选/下拉）',
						name: 'options',
						type: 'string',
						default: '',
						displayOptions: {
							show: {
								question_type: [2, 3, 15],
							},
						},
						description: '选项列表，多个选项用英文逗号分隔',
						placeholder: '例如: 选项1,选项2,选项3',
					},
					{
						displayName: '问题扩展设置',
						name: 'question_extend_setting',
						type: 'json',
						default: '{}',
						description: '问题的额外设置(JSON格式)，不同问题类型有相应的设置。详见API文档',
						hint: '高级选项，可选',
						placeholder: '{"text_setting": {"validation_type": 0}}',
					},
				],
			},
		],
	},
	{
		displayName: '收集表设置',
		name: 'formSetting',
		type: 'collection',
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加设置',
		description: '收集表的高级设置',
		options: [
			{
				displayName: '填写权限',
				name: 'fill_out_auth',
				type: 'options',
				default: 0,
				options: [
					{ name: '所有人', value: 0 },
					{ name: '企业内指定人/部门', value: 1 },
					{ name: '家校所有范围', value: 4 },
				],
			},
			{
				displayName: '指定填写人员 Names or IDs',
				name: 'fill_in_range_userids',
				type: 'multiOptions',
				typeOptions: {
					loadOptionsMethod: 'getAllUsers',
				},
				default: [],
				displayOptions: {
					show: {
						fill_out_auth: [1],
					},
				},
				description: '指定的可填写的企业成员列表',
				hint: '从列表中选择成员',
			},
			{
				displayName: '指定填写部门 Names or IDs',
				name: 'fill_in_range_departmentids',
				type: 'multiOptions',
				typeOptions: {
					loadOptionsMethod: 'getDepartments',
				},
				default: [],
				displayOptions: {
					show: {
						fill_out_auth: [1],
					},
				},
				description: '指定的可填写的部门列表',
				hint: '从列表中选择部门',
			},
			{
				displayName: '收集表管理员 Names or IDs',
				name: 'setting_manager_range',
				type: 'multiOptions',
				typeOptions: {
					loadOptionsMethod: 'getAllUsers',
				},
				default: [],
				description: '收集表管理员的企业成员列表',
				hint: '从列表中选择管理员',
			},
			{
				displayName: '定时关闭',
				name: 'timed_finish',
				type: 'dateTime',
				default: '',
				description: '定时关闭时间。定时重复与定时结束互斥，若都填，优先定时重复',
				hint: '时间不能早于当前时间',
			},
			{
				displayName: '是否允许每人提交多份',
				name: 'allow_multi_fill',
				type: 'boolean',
				default: false,
				description: '是否允许每人提交多份。默认false',
			},
			{
				displayName: '是否允许匿名填写',
				name: 'can_anonymous',
				type: 'boolean',
				default: false,
				description: '是否支持匿名填写。默认false',
			},
			{
				displayName: '是否有回复时提醒',
				name: 'can_notify_submit',
				type: 'boolean',
				default: false,
				description: '是否有回复时提醒。默认false',
			},
			{
				displayName: '定时重复设置',
				name: 'timed_repeat_info',
				type: 'json',
				default: '{}',
				description: '定时重复提醒设置(JSON格式)。详见API文档',
				hint: '高级选项，可选',
				placeholder: '{"enable": true, "repeat_type": 1, "remind_time": 1640995200}',
			},
		],
	},
];
