import type { INodeProperties } from 'n8n-workflow';
const showOnly = { resource: ['wedoc'], operation: ['createForm'] };
export const createFormDescription: INodeProperties[] = [
	{ displayName: '文档ID', name: 'docid', type: 'string', required: true, displayOptions: { show: showOnly }, default: '', description: '关联的文档docid。', hint: '文档ID' },
	{
		displayName: '收集表标题',
		name: 'form_title',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: '收集表的标题',
		hint: '标题',
	},
	{
		displayName: '收集表描述',
		name: 'form_description',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: '收集表的描述说明',
		hint: '描述',
	},
	{
		displayName: '问题列表',
		name: 'questionList',
		type: 'fixedCollection',
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加问题',
		typeOptions: { multipleValues: true },
		description: '收集表中的问题列表',
		options: [
			{
				displayName: '问题',
				name: 'questions',
				values: [
					{
						displayName: '问题标题',
						name: 'question_title',
						type: 'string',
						default: '',
						required: true,
						description: '问题的标题',
					},
					{
						displayName: '问题类型',
						name: 'question_type',
						type: 'options',
						default: 1,
						options: [
							{ name: '单行文本', value: 1 },
							{ name: '多行文本', value: 2 },
							{ name: '单选', value: 3 },
							{ name: '多选', value: 4 },
							{ name: '下拉选择', value: 5 },
							{ name: '日期', value: 6 },
							{ name: '时间', value: 7 },
							{ name: '图片', value: 8 },
							{ name: '文件', value: 9 },
							{ name: '评分', value: 10 },
							{ name: '数字', value: 11 },
							{ name: '手机号', value: 12 },
							{ name: '邮箱', value: 13 },
							{ name: '地址', value: 14 },
						],
						description: '问题的类型',
					},
					{
						displayName: '是否必填',
						name: 'is_required',
						type: 'boolean',
						default: false,
						description: '该问题是否必填',
					},
					{
						displayName: '选项（单选/多选/下拉）',
						name: 'options',
						type: 'string',
						default: '',
						displayOptions: {
							show: {
								question_type: [3, 4, 5],
							},
						},
						description: '选项列表，多个选项用英文逗号分隔',
						placeholder: '例如: 选项1,选项2,选项3',
					},
				],
			},
		],
	},
	{
		displayName: '收集表设置',
		name: 'formSetting',
		type: 'collection',
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加设置',
		description: '收集表的高级设置',
		options: [
			{
				displayName: '允许匿名填写',
				name: 'allow_anonymous',
				type: 'boolean',
				default: false,
				description: '是否允许匿名填写',
			},
			{
				displayName: '限制每人填写次数',
				name: 'limit_fill_count',
				type: 'number',
				default: 0,
				description: '每人最多填写次数，0表示不限制',
			},
			{
				displayName: '截止时间',
				name: 'deadline',
				type: 'dateTime',
				default: '',
				description: '收集表的截止时间',
			},
		],
	},
];
