import type { INodeProperties } from 'n8n-workflow';

const showOnlyForModContent = {
	resource: ['wedoc'],
	operation: ['modDocContent'],
};

export const modDocContentDescription: INodeProperties[] = [
	{
		displayName: '文档ID',
		name: 'docid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnlyForModContent },
		default: '',
	},
	{
		displayName: '操作的文档版本',
		name: 'version',
		type: 'number',
		displayOptions: { show: showOnlyForModContent },
		default: 0,
		description: '操作的文档版本，该参数可以通过获取文档内容接口获得。操作后文档版本将更新一版。要更新的文档版本与最新文档版本相差不能超过100个。操作的文档版本（可选）',
	},
	{
		displayName: '操作列表',
		name: 'requestsCollection',
		type: 'fixedCollection',
		required: true,
		displayOptions: { show: showOnlyForModContent },
		default: {},
		placeholder: '添加操作',
		typeOptions: { multipleValues: true },
		description: '文档编辑操作列表',
		options: [
			{
				displayName: '操作',
				name: 'requests',
				values: [
					{
						displayName: '操作类型',
						name: 'request_type',
						type: 'options',
						default: 'insert_text',
						options: [
							{ name: '插入文本', value: 'insert_text' },
							{ name: '插入段落', value: 'insert_paragraph' },
							{ name: '删除内容', value: 'delete_content' },
							{ name: '替换文本', value: 'replace_text' },
							{ name: '插入图片', value: 'insert_image' },
							{ name: '插入分页符', value: 'insert_page_break' },
							{ name: '插入表格', value: 'insert_table' },
							{ name: '更新文本属性', value: 'update_text_property' },
						],
						description: '要执行的操作类型',
					},
					{
						displayName: '插入位置（索引）',
						name: 'location_index',
						type: 'number',
						default: 0,
						displayOptions: {
							show: {
								request_type: [
									'insert_text',
									'insert_paragraph',
									'insert_image',
									'insert_page_break',
									'insert_table',
								],
							},
						},
						description: '在文档中的位置索引（从0开始）',
					},
					{
						displayName: '文本内容',
						name: 'text',
						type: 'string',
						default: '',
						displayOptions: { show: { request_type: ['insert_text'] } },
						description: '要插入的文本内容',
						typeOptions: { rows: 3 },
					},
					{
						displayName: '删除范围（开始位置）',
						name: 'delete_start_index',
						type: 'number',
						default: 0,
						displayOptions: { show: { request_type: ['delete_content'] } },
						description: '删除范围的开始位置索引（从0开始）',
					},
					{
						displayName: '删除范围（长度）',
						name: 'delete_length',
						type: 'number',
						default: 1,
						displayOptions: { show: { request_type: ['delete_content'] } },
						description: '删除范围的长度',
					},
					{
						displayName: '替换文本',
						name: 'replace_text_value',
						type: 'string',
						default: '',
						displayOptions: { show: { request_type: ['replace_text'] } },
						description: '要替换的文本内容',
					},
					{
						displayName: '替换范围列表',
						name: 'rangesCollection',
						type: 'fixedCollection',
						displayOptions: { show: { request_type: ['replace_text', 'update_text_property'] } },
						default: {},
						placeholder: '添加范围',
						typeOptions: { multipleValues: true },
						description: '要替换的文档范围列表（ranges个数不超过10）',
						options: [
							{
								displayName: '范围',
								name: 'ranges',
								values: [
									{
										displayName: '开始位置',
										name: 'start_index',
										type: 'number',
										default: 0,
										description: '起始位置索引（从0开始）',
									},
									{
										displayName: '长度',
										name: 'length',
										type: 'number',
										default: 1,
										description: '范围长度',
									},
								],
							},
						],
					},
					{
						displayName: '图片URL',
						name: 'image_id',
						type: 'string',
						default: '',
						displayOptions: { show: { request_type: ['insert_image'] } },
						description: '图片URL，通过上传图片接口获得',
					},
					{
						displayName: '图片宽度（像素）',
						name: 'image_width',
						type: 'number',
						default: 0,
						displayOptions: { show: { request_type: ['insert_image'] } },
						description: '图片的宽，单位是像素（px）',
					},
					{
						displayName: '图片高度（像素）',
						name: 'image_height',
						type: 'number',
						default: 0,
						displayOptions: { show: { request_type: ['insert_image'] } },
						description: '图片的高，单位是像素（px）',
					},
					{
						displayName: '表格行数',
						name: 'table_rows',
						type: 'number',
						default: 2,
						displayOptions: { show: { request_type: ['insert_table'] } },
						description: '表格行数（行数<=100，列数<=60，单元格总数<=1000）',
					},
					{
						displayName: '表格列数',
						name: 'table_cols',
						type: 'number',
						default: 2,
						displayOptions: { show: { request_type: ['insert_table'] } },
						description: '表格列数（行数<=100，列数<=60，单元格总数<=1000）',
					},
					{
						displayName: '文本属性',
						name: 'textPropertyCollection',
						type: 'fixedCollection',
						displayOptions: { show: { request_type: ['update_text_property'] } },
						default: {},
						description: '文本属性设置',
						options: [
							{
								displayName: '属性',
								name: 'text_property',
								values: [
									{
										displayName: '是否加粗',
										name: 'bold',
										type: 'boolean',
										default: false,
									},
									{
										displayName: '文字颜色',
										name: 'color',
										type: 'color',
										default: '000000',
										description:
											'文字颜色，十六进制RRGGBB格式（如：000000表示黑色，FF0000表示红色）',
									},
									{
										displayName: '背景颜色',
										name: 'background_color',
										type: 'color',
										default: '',
										description: '文字的背景颜色，十六进制RRGGBB格式（如：0000FF表示蓝色）',
									},
								],
							},
						],
					},
				],
			},
		],
	},
];
