import type { INodeProperties } from 'n8n-workflow';

const showOnlyForModSheet = {
	resource: ['wedoc'],
	operation: ['modSheetContent'],
};

export const modSheetContentDescription: INodeProperties[] = [
	{
		displayName: '文档ID',
		name: 'docid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnlyForModSheet },
		default: '',
		description: '表格文档的docid',
		hint: '文档ID',
	},
	{
		displayName: '操作列表',
		name: 'requestsCollection',
		type: 'fixedCollection',
		required: true,
		displayOptions: { show: showOnlyForModSheet },
		default: {},
		placeholder: '添加操作',
		typeOptions: { multipleValues: true },
		description: '表格编辑操作列表',
		options: [
			{
				displayName: '操作',
				name: 'requests',
				values: [
					{
						displayName: '操作类型',
						name: 'request_type',
						type: 'options',
						default: 'update_range',
						options: [
							{ name: '更新单元格', value: 'update_range' },
							{ name: '追加行', value: 'append_rows' },
							{ name: '插入行', value: 'insert_rows' },
							{ name: '删除行', value: 'delete_rows' },
							{ name: '插入列', value: 'insert_columns' },
							{ name: '删除列', value: 'delete_columns' },
						],
						description: '要执行的操作类型',
					},
					{
						displayName: '工作表名称',
						name: 'sheet_name',
						type: 'string',
						default: 'Sheet1',

					},
					{
						displayName: '单元格范围',
						name: 'range',
						type: 'string',
						default: 'A1',
						displayOptions: { show: { request_type: ['update_range'] } },
						description: '要更新的单元格范围',
						placeholder: '例如: A1 或 A1:C3',
						hint: '支持单个单元格或范围',
					},
					{
						displayName: '单元格值',
						name: 'values',
						type: 'string',
						default: '',
						displayOptions: { show: { request_type: ['update_range', 'append_rows'] } },
						description: '单元格值：多值用逗号分隔，多行用分号分隔',
						placeholder: '例如: 值1,值2,值3;值4,值5,值6',
						typeOptions: { rows: 3 },
					},
					{
						displayName: '起始行号',
						name: 'row_index',
						type: 'number',
						default: 1,
						displayOptions: { show: { request_type: ['insert_rows', 'delete_rows'] } },
						description: '操作的起始行号（从1开始）',
						typeOptions: { minValue: 1 },
					},
					{
						displayName: '行数',
						name: 'row_count',
						type: 'number',
						default: 1,
						displayOptions: { show: { request_type: ['insert_rows', 'delete_rows'] } },
						description: '要插入或删除的行数',
						typeOptions: { minValue: 1 },
					},
					{
						displayName: '起始列号',
						name: 'column_index',
						type: 'number',
						default: 1,
						displayOptions: { show: { request_type: ['insert_columns', 'delete_columns'] } },
						description: '操作的起始列号（从1开始）',
						typeOptions: { minValue: 1 },
					},
					{
						displayName: '列数',
						name: 'column_count',
						type: 'number',
						default: 1,
						displayOptions: { show: { request_type: ['insert_columns', 'delete_columns'] } },
						description: '要插入或删除的列数',
						typeOptions: { minValue: 1 },
					},
				],
			},
		],
	},
];
