import type { INodeProperties } from 'n8n-workflow';

const showOnlyForModSheet = {
	resource: ['wedoc'],
	operation: ['modSheetContent'],
};

export const modSheetContentDescription: INodeProperties[] = [
	{
		displayName: '文档ID',
		name: 'docid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnlyForModSheet },
		default: '',
		description: '表格文档的docid。文档ID',
	},
	{
		displayName: '操作列表',
		name: 'requestsCollection',
		type: 'fixedCollection',
		required: true,
		displayOptions: { show: showOnlyForModSheet },
		default: {},
		placeholder: '添加操作',
		typeOptions: { multipleValues: true },
		description: '表格编辑操作列表',
		options: [
			{
				displayName: '操作',
				name: 'requests',
				values: [
					{
						displayName: '操作类型',
						name: 'request_type',
						type: 'options',
						default: 'update_range',
						options: [
							{ name: '新增工作表', value: 'add_sheet' },
							{ name: '删除工作表', value: 'delete_sheet' },
							{ name: '更新单元格', value: 'update_range' },
							{ name: '删除行或列', value: 'delete_dimension' },
						],
						description: '要执行的操作类型（单次批量更新请求的操作数量 <= 5）',
					},
					{
						displayName: '工作表ID',
						name: 'sheet_id',
						type: 'string',
						default: '',
						displayOptions: {
							show: { request_type: ['delete_sheet', 'update_range', 'delete_dimension'] },
						},
						description: '工作表唯一标识',
						placeholder: '例如: AAAAA',
					},
					{
						displayName: '新增工作表名称',
						name: 'title',
						type: 'string',
						default: '',
						displayOptions: { show: { request_type: ['add_sheet'] } },
						description: '新增工作表的名称',
						placeholder: '例如: 新工作表',
					},
					{
						displayName: '行数',
						name: 'add_sheet_row_count',
						type: 'number',
						default: 10,
						displayOptions: { show: { request_type: ['add_sheet'] } },
						description: '新增工作表的行数（最多1000行）',
						typeOptions: { minValue: 1, maxValue: 1000 },
					},
					{
						displayName: '列数',
						name: 'add_sheet_column_count',
						type: 'number',
						default: 10,
						displayOptions: { show: { request_type: ['add_sheet'] } },
						description: '新增工作表的列数（最多200列）',
						typeOptions: { minValue: 1, maxValue: 200 },
					},
					{
						displayName: '起始行号',
						name: 'start_row',
						type: 'number',
						default: 1,
						displayOptions: { show: { request_type: ['update_range'] } },
						description: '更新范围的起始行号（从1开始，范围行数 <=1000）',
						typeOptions: { minValue: 1 },
					},
					{
						displayName: '起始列号',
						name: 'start_column',
						type: 'number',
						default: 1,
						displayOptions: { show: { request_type: ['update_range'] } },
						description: '更新范围的起始列号（从1开始，范围列数 <=200）',
						typeOptions: { minValue: 1 },
					},
					{
						displayName: '行数',
						name: 'row_count',
						type: 'number',
						default: 1,
						displayOptions: { show: { request_type: ['update_range'] } },
						description: '更新范围的行数（范围行数 <=1000，总单元格数量 <=10000）',
						typeOptions: { minValue: 1, maxValue: 1000 },
					},
					{
						displayName: '列数',
						name: 'column_count',
						type: 'number',
						default: 1,
						displayOptions: { show: { request_type: ['update_range'] } },
						description: '更新范围的列数（范围列数 <=200，总单元格数量 <=10000）',
						typeOptions: { minValue: 1, maxValue: 200 },
					},
					{
						displayName: '单元格值',
						name: 'values',
						type: 'string',
						default: '',
						displayOptions: { show: { request_type: ['update_range'] } },
						description: '单元格值：多值用逗号分隔，多行用分号分隔',
						placeholder: '例如: 值1,值2,值3;值4,值5,值6',
						typeOptions: { rows: 3 },
					},
					{
						displayName: '删除维度',
						name: 'dimension',
						type: 'options',
						default: 'ROW',
						displayOptions: { show: { request_type: ['delete_dimension'] } },
						options: [
							{ name: '行', value: 'ROW' },
							{ name: '列', value: 'COLUMN' },
						],
						description: '声明删除的维度为行或者列',
					},
					{
						displayName: '起始序号',
						name: 'start_index',
						type: 'number',
						default: 1,
						displayOptions: { show: { request_type: ['delete_dimension'] } },
						description: '删除行列的起始序号（从1开始，左闭右开区间）',
						typeOptions: { minValue: 1 },
					},
					{
						displayName: '终止序号',
						name: 'end_index',
						type: 'number',
						default: 2,
						displayOptions: { show: { request_type: ['delete_dimension'] } },
						description: '删除行列的终止序号（从1开始，左闭右开区间，必须大于起始序号）。例如: 起始=1，结束=3，将删除第1和第2行（或列）',
						typeOptions: { minValue: 2 },
					},
				],
			},
		],
	},
];
