import type { INodeProperties } from 'n8n-workflow';
const showOnly = { resource: ['wedoc'], operation: ['querySmartsheetRecord'] };
export const querySmartsheetRecordDescription: INodeProperties[] = [
	{
		displayName: '文档ID',
		name: 'docid',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: '智能表格的docid。文档ID',
	},
	{
		displayName: '子表ID',
		name: 'sheet_id',
		type: 'string',
		required: true,
		displayOptions: { show: showOnly },
		default: '',
		description: '子表的sheet_id。子表ID',
	},
	{
		displayName: '视图ID',
		name: 'view_id',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: '视图的view_id。不填则使用默认视图。视图ID（可选）',
	},
	{
		displayName: '返回Key类型',
		name: 'key_type',
		type: 'options',
		displayOptions: { show: showOnly },
		default: 'CELL_VALUE_KEY_TYPE_FIELD_TITLE',
		options: [
			{
				name: '字段标题',
				value: 'CELL_VALUE_KEY_TYPE_FIELD_TITLE',
				description: '使用字段标题作为返回数据的key（推荐，更易读）',
			},
			{
				name: '字段ID',
				value: 'CELL_VALUE_KEY_TYPE_FIELD_ID',
				description: '使用字段ID作为返回数据的key',
			},
		],
		description: '指定返回记录中字段值的key类型',
	},
	{
		displayName: '指定记录ID',
		name: 'record_ids',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		description: '指定要查询的记录ID列表，用逗号分隔。不填则查询所有符合条件的记录。',
		placeholder: '如: record_001,record_002',
	},
	{
		displayName: '筛选条件',
		name: 'filterConditions',
		type: 'fixedCollection',
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加筛选条件',
		typeOptions: { multipleValues: true },
		description: '配置记录筛选条件。⚠️ 注意：筛选条件不能与排序规则同时使用',
		options: [
			{
				displayName: '条件',
				name: 'conditions',
				values: [
					{
						displayName: '字段ID',
						name: 'field_id',
						type: 'string',
						default: '',
						required: true,
						description: '要筛选的字段ID',
						placeholder: '如: f53B4X',
					},
					{
						displayName: '字段类型',
						name: 'field_type',
						type: 'options',
						default: 'FIELD_TYPE_TEXT',
						options: [
							{ name: '文本', value: 'FIELD_TYPE_TEXT' },
							{ name: '数字', value: 'FIELD_TYPE_NUMBER' },
							{ name: '单选', value: 'FIELD_TYPE_SINGLE_SELECT' },
							{ name: '多选', value: 'FIELD_TYPE_MULTI_SELECT' },
							{ name: '日期', value: 'FIELD_TYPE_DATE' },
							{ name: '人员', value: 'FIELD_TYPE_USER' },
							{ name: '附件', value: 'FIELD_TYPE_ATTACHMENT' },
							{ name: '复选框', value: 'FIELD_TYPE_CHECKBOX' },
							{ name: '链接', value: 'FIELD_TYPE_URL' },
							{ name: '电话', value: 'FIELD_TYPE_PHONE' },
							{ name: '邮箱', value: 'FIELD_TYPE_EMAIL' },
							{ name: '地理位置', value: 'FIELD_TYPE_LOCATION' },
							{ name: '自动编号', value: 'FIELD_TYPE_AUTO_NUMBER' },
						],
						description: '字段的类型',
					},
					{
						displayName: '操作符',
						name: 'operator',
						type: 'options',
						default: 'OPERATOR_EQUAL',
						options: [
							{ name: '等于', value: 'OPERATOR_EQUAL' },
							{ name: '不等于', value: 'OPERATOR_NOT_EQUAL' },
							{ name: '大于', value: 'OPERATOR_GREATER' },
							{ name: '大于等于', value: 'OPERATOR_GREATER_EQUAL' },
							{ name: '小于', value: 'OPERATOR_LESS' },
							{ name: '小于等于', value: 'OPERATOR_LESS_EQUAL' },
							{ name: '包含', value: 'OPERATOR_CONTAINS' },
							{ name: '不包含', value: 'OPERATOR_NOT_CONTAINS' },
							{ name: '为空', value: 'OPERATOR_IS_EMPTY' },
							{ name: '不为空', value: 'OPERATOR_IS_NOT_EMPTY' },
							{ name: '在列表中', value: 'OPERATOR_IN' },
							{ name: '不在列表中', value: 'OPERATOR_NOT_IN' },
						],
						description: '筛选操作符',
					},
					{
						displayName: '值',
						name: 'value',
						type: 'string',
						default: '',
						displayOptions: {
							hide: {
								operator: ['OPERATOR_IS_EMPTY', 'OPERATOR_IS_NOT_EMPTY'],
							},
						},
						description: '筛选值，多个值用逗号分隔',
						placeholder: '如: 张三 或 值1,值2,值3',
					},
				],
			},
		],
	},
	{
		displayName: '条件关系',
		name: 'conjunction',
		type: 'options',
		displayOptions: { show: showOnly },
		default: 'CONJUNCTION_AND',
		options: [
			{ name: '满足所有条件 (AND)', value: 'CONJUNCTION_AND' },
			{ name: '满足任一条件 (OR)', value: 'CONJUNCTION_OR' },
		],
		description: '当有多个筛选条件时，它们之间的关系',
	},
	{
		displayName: '排序规则',
		name: 'sort',
		type: 'fixedCollection',
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加排序规则',
		typeOptions: { multipleValues: true },
		description: '配置记录排序规则。⚠️ 注意：排序规则不能与筛选条件同时使用',
		options: [
			{
				displayName: '排序',
				name: 'rules',
				values: [
					{
						displayName: '排序字段类型',
						name: 'sort_key_type',
						type: 'options',
						default: 'field_title',
						options: [
							{ name: '使用字段标题', value: 'field_title' },
							{ name: '使用字段ID', value: 'field_id' },
						],
						description: '选择使用字段ID还是字段标题进行排序',
					},
					{
						displayName: '字段标题',
						name: 'field_title',
						type: 'string',
						default: '',
						displayOptions: {
							show: {
								sort_key_type: ['field_title'],
							},
						},
						required: true,
						description: '要排序的字段标题',
						placeholder: '如: 创建时间',
					},
					{
						displayName: '字段ID',
						name: 'field_id',
						type: 'string',
						default: '',
						displayOptions: {
							show: {
								sort_key_type: ['field_id'],
							},
						},
						required: true,
						description: '要排序的字段ID',
						placeholder: '如: field_001',
					},
					{
						displayName: '排序方向',
						name: 'desc',
						type: 'options',
						default: false,
						options: [
							{ name: '升序 (ASC)', value: false },
							{ name: '降序 (DESC)', value: true },
						],
					},
				],
			},
		],
	},
	{
		displayName: '分页设置',
		name: 'pagination',
		type: 'collection',
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '添加分页参数',
		description: '配置分页参数',
		options: [
			{
				displayName: '每页记录数',
				name: 'limit',
				type: 'number',
				default: 50,
				typeOptions: {
					minValue: 1,
					maxValue: 1000,
				},
				description: '每页返回多少条数据，最大值 1000。默认50条',
			},
			{
				displayName: '偏移量',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: {
					minValue: 0,
				},
				description: '从第几条记录开始返回（用于分页）',
			},
		],
	},
	{
		displayName: '返回字段',
		name: 'returnFields',
		type: 'collection',
		displayOptions: { show: showOnly },
		default: {},
		placeholder: '指定返回字段',
		description: '指定要返回的字段，留空则返回所有字段',
		options: [
			{
				displayName: '字段ID列表',
				name: 'field_ids',
				type: 'string',
				default: '',
				description: '指定返回的字段ID列表，用逗号分隔',
				placeholder: '如: f53B4X,field_002',
			},
			{
				displayName: '字段标题列表',
				name: 'field_titles',
				type: 'string',
				default: '',
				description: '指定返回的字段标题列表，用逗号分隔。当返回Key类型为字段标题时使用。',
				placeholder: '如: 姓名,年龄,部门',
			},
		],
	},
];
