import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['externalContact'], operation: ['addContactWay'] };

export const addContactWayDescription: INodeProperties[] = [
	{
		displayName: '联系方式类型',
		name: 'type',
		type: 'options',
		options: [
			{ name: '单人', value: 1 },
			{ name: '多人', value: 2 },
		],
		required: true,
		default: 1,
		displayOptions: { show: showOnly },
		description: '联系方式类型。1-单人，客户添加时自动成为该成员的客户；2-多人，客户可选择其中一位成员进行添加',
	},
	{
		displayName: '场景',
		name: 'scene',
		type: 'options',
		options: [
			{ name: '在小程序中联系', value: 1 },
			{ name: '通过二维码联系', value: 2 },
		],
		required: true,
		default: 2,
		displayOptions: { show: showOnly },
		description: '场景。1-在小程序中联系；2-通过二维码联系',
	},
	{
		displayName: '配置的成员列表',
		name: 'user',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		description: '使用该联系方式的企业成员UserID列表，多个用英文逗号分隔',
		placeholder: 'zhangsan,lisi',
	},
	{
		displayName: '备注',
		name: 'remark',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		description: '联系方式的备注信息，用于管理员自己识别',
		placeholder: '官网二维码',
	},
	{
		displayName: '跳过验证',
		name: 'skip_verify',
		type: 'boolean',
		default: true,
		displayOptions: { show: showOnly },
		description: '外部客户添加时是否无需验证，默认为true（自动通过）',
	},
	{
		displayName: '设置结束语',
		name: 'enableConclusions',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否设置结束语',
	},
	{
		displayName: '结束语类型',
		name: 'conclusionType',
		type: 'options',
		displayOptions: { show: { ...showOnly, enableConclusions: [true] } },
		options: [
			{ name: '文本', value: 'text' },
			{ name: '图片', value: 'image' },
			{ name: '链接', value: 'link' },
			{ name: '小程序', value: 'miniprogram' },
		],
		default: 'text',
		description: '结束语消息类型',
	},
	{
		displayName: '文本内容',
		name: 'conclusion_text',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['text'] } },
		default: '',
		description: '结束语文本内容',
		placeholder: '感谢您的咨询',
	},
	{
		displayName: '图片Media ID',
		name: 'conclusion_image_media_id',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['image'] } },
		default: '',
		description: '结束语图片的media_id',
	},
	{
		displayName: '链接标题',
		name: 'conclusion_link_title',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['link'] } },
		default: '',

	},
	{
		displayName: '链接封面URL',
		name: 'conclusion_link_picurl',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['link'] } },
		default: '',
		description: '链接封面图URL',
	},
	{
		displayName: '链接描述',
		name: 'conclusion_link_desc',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['link'] } },
		default: '',

	},
	{
		displayName: '链接URL',
		name: 'conclusion_link_url',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['link'] } },
		default: '',
		description: '链接跳转URL',
	},
	{
		displayName: '小程序标题',
		name: 'conclusion_miniprogram_title',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['miniprogram'] } },
		default: '',

	},
	{
		displayName: '小程序AppID',
		name: 'conclusion_miniprogram_appid',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['miniprogram'] } },
		default: '',
		description: '小程序的AppID',
	},
	{
		displayName: '小程序页面路径',
		name: 'conclusion_miniprogram_pagepath',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['miniprogram'] } },
		default: '',

	},
	{
		displayName: '小程序封面Media ID',
		name: 'conclusion_miniprogram_pic_media_id',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['miniprogram'] } },
		default: '',
		description: '小程序封面图的media_id',
	},
];
