import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['externalContact'], operation: ['addContactWay'] };

export const addContactWayDescription: INodeProperties[] = [
	{
		displayName: '联系方式类型',
		name: 'type',
		type: 'options',
		options: [
			{ name: '单人', value: 1 },
			{ name: '多人', value: 2 },
		],
		required: true,
		default: 1,
		displayOptions: { show: showOnly },
		description: '联系方式类型。1-单人，客户添加时自动成为该成员的客户；2-多人，客户可选择其中一位成员进行添加',
	},
	{
		displayName: '场景',
		name: 'scene',
		type: 'options',
		options: [
			{ name: '在小程序中联系', value: 1 },
			{ name: '通过二维码联系', value: 2 },
		],
		required: true,
		default: 2,
		displayOptions: { show: showOnly },
		description: '场景。1-在小程序中联系；2-通过二维码联系',
	},
	{
		displayName: '样式',
		name: 'style',
		type: 'options',
		options: [
			{ name: '样式1', value: 1 },
			{ name: '样式2', value: 2 },
			{ name: '样式3', value: 3 },
		],
		default: 1,
		displayOptions: { show: { ...showOnly, scene: [1] } },
		description: '在小程序中联系时使用的控件样式',
	},
	{
		displayName: '配置的成员列表',
		name: 'user',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		description: '使用该联系方式的用户userID列表，多个用英文逗号分隔。在type为1时为必填，且只能有一个',
		placeholder: 'zhangsan,lisi',
	},
	{
		displayName: '配置的部门列表',
		name: 'party',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, type: [2] } },
		description: '使用该联系方式的部门ID列表，多个用英文逗号分隔，只在type为2时有效',
		placeholder: '1,2,3',
	},
	{
		displayName: '备注',
		name: 'remark',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		description: '联系方式的备注信息，用于助记，不超过30个字符',
		placeholder: '渠道客户',
	},
	{
		displayName: '跳过验证',
		name: 'skip_verify',
		type: 'boolean',
		default: true,
		displayOptions: { show: showOnly },
		description: '外部客户添加时是否无需验证，默认为true',
	},
	{
		displayName: '自定义State参数',
		name: 'state',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		description: '企业自定义的state参数，用于区分不同的添加渠道，在调用"获取客户详情"时会返回该参数值，不超过30个字符',
		placeholder: 'teststate',
	},
	{
		displayName: '临时会话模式',
		name: 'is_temp',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否临时会话模式，true表示使用临时会话模式，默认为false。临时会话模式仅支持医疗行业企业创建',
	},
	{
		displayName: '二维码有效期（秒）',
		name: 'expires_in',
		type: 'number',
		default: 604800,
		displayOptions: { show: { ...showOnly, is_temp: [true] } },
		description: '临时会话二维码有效期，以秒为单位。默认7天（604800秒），最多为14天（1209600秒）',
	},
	{
		displayName: '会话有效期（秒）',
		name: 'chat_expires_in',
		type: 'number',
		default: 86400,
		displayOptions: { show: { ...showOnly, is_temp: [true] } },
		description: '临时会话有效期，以秒为单位。默认为添加好友后24小时（86400秒），最多为14天',
	},
	{
		displayName: '客户UnionID',
		name: 'unionid',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, is_temp: [true] } },
		description: '可进行临时会话的客户unionid，如不指定则不进行限制',
		placeholder: 'oxTWIuGaIt6gTKsQRLau2M0AAAA',
	},
	{
		displayName: '同企业客户只能添加同一员工',
		name: 'is_exclusive',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否开启同一外部企业客户只能添加同一个员工，开启后，同一个企业的客户会优先添加到同一个跟进人',
	},
	{
		displayName: '标记客户来源',
		name: 'mark_source',
		type: 'boolean',
		default: true,
		displayOptions: { show: showOnly },
		description: '是否标记客户添加来源为该应用创建的「联系我」，仅对「营销获客」应用生效',
	},
	{
		displayName: '设置结束语',
		name: 'enableConclusions',
		type: 'boolean',
		default: false,
		displayOptions: { show: { ...showOnly, is_temp: [true] } },
		description: '是否设置结束语，会话结束时自动发送给客户，仅在临时会话模式下有效',
	},
	{
		displayName: '结束语类型',
		name: 'conclusionType',
		type: 'options',
		displayOptions: { show: { ...showOnly, is_temp: [true], enableConclusions: [true] } },
		options: [
			{ name: '文本', value: 'text' },
			{ name: '图片', value: 'image' },
			{ name: '链接', value: 'link' },
			{ name: '小程序', value: 'miniprogram' },
		],
		default: 'text',
		description: '结束语消息类型。text与另外三者可以同时发送，image、link和miniprogram只能有一个',
	},
	{
		displayName: '文本内容',
		name: 'conclusion_text',
		type: 'string',
		typeOptions: { rows: 3 },
		displayOptions: { show: { ...showOnly, is_temp: [true], enableConclusions: [true], conclusionType: ['text'] } },
		default: '',
		description: '消息文本内容，最长为4000字节',
		placeholder: '感谢您的咨询',
	},
	{
		displayName: '图片Media ID',
		name: 'conclusion_image_media_id',
		type: 'string',
		displayOptions: { show: { ...showOnly, is_temp: [true], enableConclusions: [true], conclusionType: ['image'] } },
		default: '',
		description: '图片的media_id，可通过素材管理接口获得',
	},
	{
		displayName: '链接标题',
		name: 'conclusion_link_title',
		type: 'string',
		displayOptions: { show: { ...showOnly, is_temp: [true], enableConclusions: [true], conclusionType: ['link'] } },
		default: '',
		description: '图文消息标题，最长为128字节',
	},
	{
		displayName: '链接封面URL',
		name: 'conclusion_link_picurl',
		type: 'string',
		displayOptions: { show: { ...showOnly, is_temp: [true], enableConclusions: [true], conclusionType: ['link'] } },
		default: '',
		description: '图文消息封面的URL',
	},
	{
		displayName: '链接描述',
		name: 'conclusion_link_desc',
		type: 'string',
		displayOptions: { show: { ...showOnly, is_temp: [true], enableConclusions: [true], conclusionType: ['link'] } },
		default: '',
		description: '图文消息的描述，最长为512字节',
	},
	{
		displayName: '链接URL',
		name: 'conclusion_link_url',
		type: 'string',
		displayOptions: { show: { ...showOnly, is_temp: [true], enableConclusions: [true], conclusionType: ['link'] } },
		default: '',
		description: '图文消息的链接',
	},
	{
		displayName: '小程序标题',
		name: 'conclusion_miniprogram_title',
		type: 'string',
		displayOptions: { show: { ...showOnly, is_temp: [true], enableConclusions: [true], conclusionType: ['miniprogram'] } },
		default: '',
		description: '小程序消息标题，最长为64字节',
	},
	{
		displayName: '小程序AppID',
		name: 'conclusion_miniprogram_appid',
		type: 'string',
		displayOptions: { show: { ...showOnly, is_temp: [true], enableConclusions: [true], conclusionType: ['miniprogram'] } },
		default: '',
		description: '小程序appid，必须是关联到企业的小程序应用',
	},
	{
		displayName: '小程序页面路径',
		name: 'conclusion_miniprogram_page',
		type: 'string',
		displayOptions: { show: { ...showOnly, is_temp: [true], enableConclusions: [true], conclusionType: ['miniprogram'] } },
		default: '',
		description: '小程序page路径',
		placeholder: '/path/index.html',
	},
	{
		displayName: '小程序封面Media ID',
		name: 'conclusion_miniprogram_pic_media_id',
		type: 'string',
		displayOptions: { show: { ...showOnly, is_temp: [true], enableConclusions: [true], conclusionType: ['miniprogram'] } },
		default: '',
		description: '小程序消息封面的mediaid，封面图建议尺寸为520*416',
	},
];
