import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['externalContact'], operation: ['addMomentTask'] };

export const addMomentTaskDescription: INodeProperties[] = [
	{
		displayName: '指定发表范围',
		name: 'enableVisibleRange',
		type: 'boolean',
		default: true,
		displayOptions: { show: showOnly },
		description: '是否指定发表范围。若未指定，则执行者为应用可见范围内所有成员',
	},
	{
		displayName: '发表成员列表',
		name: 'sender_user_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, enableVisibleRange: [true] } },
		description: '发表任务的执行者用户列表，多个UserID用逗号分隔，最多支持10万个',
		placeholder: 'zhangshan,lisi',
	},
	{
		displayName: '发表部门列表',
		name: 'sender_department_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, enableVisibleRange: [true] } },
		description: '发表任务的执行者部门列表，多个部门ID用逗号分隔',
		placeholder: '2,3',
	},
	{
		displayName: '指定可见客户',
		name: 'enableExternalContactList',
		type: 'boolean',
		default: false,
		displayOptions: { show: { ...showOnly, enableVisibleRange: [true] } },
		description: '是否指定可见到该朋友圈的客户列表（通过客户标签指定）。若指定，则该朋友圈为部分可见',
	},
	{
		displayName: '可见客户标签列表',
		name: 'external_contact_tag_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, enableVisibleRange: [true], enableExternalContactList: [true] } },
		description: '可见到该朋友圈的客户标签列表，多个标签ID用逗号分隔。注：仅支持企业客户标签，不支持规则组标签',
		placeholder: 'etXXXXXXXXXX,etYYYYYYYYYY',
	},
	{
		displayName: '朋友圈内容类型',
		name: 'contentType',
		type: 'options',
		required: true,
		displayOptions: { show: showOnly },
		options: [
			{ name: '纯文本', value: 'text' },
			{ name: '图片', value: 'image' },
			{ name: '视频', value: 'video' },
			{ name: '链接', value: 'link' },
		],
		default: 'text',
		description: '朋友圈内容类型。附件最多支持9个图片，或者1个视频，或者1个链接',
	},
	{
		displayName: '文本内容',
		name: 'text_content',
		type: 'string',
		displayOptions: { show: showOnly },
		default: '',
		typeOptions: { rows: 4 },
		description: '消息文本内容，不能与附件同时为空，最多支持2000个字（4000个字节）',
		placeholder: '今天是个好日子...',
	},
	{
		displayName: '图片列表',
		name: 'imageCollection',
		type: 'fixedCollection',
		displayOptions: { show: { ...showOnly, contentType: ['image'] } },
		default: {},
		placeholder: '添加图片',
		typeOptions: { multipleValues: true },
		description: '图片附件列表，最多9张。长边不超过10800像素，短边不超过1080像素',
		options: [
			{
				displayName: '图片',
				name: 'images',
				values: [
					{
						displayName: 'Media ID',
						name: 'media_id',
						type: 'string',
						default: '',
						required: true,
						description: '图片的media_id，可通过上传附件资源接口获得',
					},
				],
			},
		],
	},
	{
		displayName: '视频Media ID',
		name: 'video_media_id',
		type: 'string',
		displayOptions: { show: { ...showOnly, contentType: ['video'] } },
		default: '',
		description: '视频的素材ID，最长不超过30S，最大不超过10MB。可通过上传附件资源接口获得',
	},
	{
		displayName: '链接标题',
		name: 'link_title',
		type: 'string',
		displayOptions: { show: { ...showOnly, contentType: ['link'] } },
		default: '',
		description: '图文消息标题，最多64个字（128个字节）',
	},
	{
		displayName: '链接URL',
		name: 'link_url',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, contentType: ['link'] } },
		default: '',
		description: '图文消息链接',
	},
	{
		displayName: '链接封面Media ID',
		name: 'link_media_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, contentType: ['link'] } },
		default: '',
		description: '图片链接封面的media_id，长边不超过10800像素，短边不超过1080像素，可通过上传附件资源接口获得',
	},
];
