import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['externalContact'], operation: ['updateCustomerAcquisitionLink'] };

export const updateCustomerAcquisitionLinkDescription: INodeProperties[] = [
	{
		displayName: '链接ID',
		name: 'link_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: showOnly },
		description: '获客链接的ID，需要是当前应用创建',
	},
	{
		displayName: '链接名称',
		name: 'link_name',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		description: '更新的链接名称，最长为30个字符',
	},
	{
		displayName: '更新使用范围',
		name: 'updateRange',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否更新使用范围（覆盖更新）',
	},
	{
		displayName: '使用范围类型',
		name: 'rangeType',
		type: 'options',
		displayOptions: { show: { ...showOnly, updateRange: [true] } },
		options: [
			{ name: '指定成员', value: 'user', description: '指定成员可使用此链接' },
			{ name: '指定部门', value: 'department', description: '指定部门可使用此链接' },
		],
		default: 'user',
		description: '使用范围类型，覆盖的总人数不能超过500人',
	},
	{
		displayName: '成员列表',
		name: 'user_list',
		type: 'string',
		displayOptions: { show: { ...showOnly, updateRange: [true], rangeType: ['user'] } },
		default: '',
		description: '此获客链接关联的userid列表，多个用逗号分隔，最多可关联500个',
		placeholder: 'zhangsan,lisi',
	},
	{
		displayName: '部门列表',
		name: 'department_list',
		type: 'string',
		displayOptions: { show: { ...showOnly, updateRange: [true], rangeType: ['department'] } },
		default: '',
		description: '此获客链接关联的部门ID列表，多个用逗号分隔，部门覆盖总人数最多500个',
		placeholder: '2,3',
	},
	{
		displayName: '跳过验证',
		name: 'skip_verify',
		type: 'boolean',
		default: true,
		displayOptions: { show: showOnly },
		description: '是否无需验证，默认为true',
	},
	{
		displayName: '标记客户来源',
		name: 'mark_source',
		type: 'boolean',
		default: true,
		displayOptions: { show: showOnly },
		description: '是否标记客户添加来源为该应用创建的获客链接，仅对「营销获客」应用生效',
	},
	{
		displayName: '更新优先分配配置',
		name: 'updatePriorityOption',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否更新客户与成员关系绑定配置（覆盖更新，仅部分经营类目企业支持）',
	},
	{
		displayName: '优先分配类型',
		name: 'priority_type',
		type: 'options',
		options: [
			{ name: '全企业范围内优先分配给有好友关系的', value: 1 },
			{ name: '指定范围内优先分配有好友关系的', value: 2 },
		],
		default: 1,
		displayOptions: { show: { ...showOnly, updatePriorityOption: [true] } },
		description: '客户与成员关系绑定类型',
	},
	{
		displayName: '优先分配成员列表',
		name: 'priority_userid_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, updatePriorityOption: [true], priority_type: [2] } },
		description: '指定成员列表，多个用逗号分隔，priority_type为2时必填，最多1000个',
		placeholder: 'tom,lisi',
	},
];
