import type { INodeProperties } from 'n8n-workflow';

const showOnly = {
	resource: ['externalContact'],
	operation: ['updateContactWay'],
};

export const updateContactWayDescription: INodeProperties[] = [
	{
		displayName: '联系方式配置ID',
		name: 'config_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: showOnly },
		description: '企业联系方式的配置ID',
		placeholder: '42b34949e138eb6e027c123cba77fAAA',
	},
	{
		displayName: '配置的成员列表',
		name: 'user',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		description: '使用该联系方式的用户列表，多个用英文逗号分隔，将覆盖原有用户列表',
		placeholder: 'zhangsan,lisi,wangwu',
	},
	{
		displayName: '配置的部门列表',
		name: 'party',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		description: '使用该联系方式的部门列表，多个用英文逗号分隔，将覆盖原有部门列表，只在配置的type为2时有效',
		placeholder: '2,3',
	},
	{
		displayName: '备注',
		name: 'remark',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		description: '联系方式的备注信息，不超过30个字符，将覆盖之前的备注',
		placeholder: '渠道客户',
	},
	{
		displayName: '跳过验证',
		name: 'skip_verify',
		type: 'boolean',
		default: true,
		displayOptions: { show: showOnly },
		description: '外部客户添加时是否无需验证',
	},
	{
		displayName: '样式',
		name: 'style',
		type: 'options',
		options: [
			{ name: '不修改', value: 0 },
			{ name: '样式1', value: 1 },
			{ name: '样式2', value: 2 },
			{ name: '样式3', value: 3 },
		],
		default: 0,
		displayOptions: { show: showOnly },
		description: '样式，只针对"在小程序中联系"的配置生效',
	},
	{
		displayName: '自定义State参数',
		name: 'state',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		description: '企业自定义的state参数，用于区分不同的添加渠道，在调用"获取客户详情"时会返回该参数值',
		placeholder: 'teststate',
	},
	{
		displayName: '二维码有效期（秒）',
		name: 'expires_in',
		type: 'number',
		default: 0,
		displayOptions: { show: showOnly },
		description: '临时会话二维码有效期，以秒为单位。仅在临时会话模式下有效',
	},
	{
		displayName: '会话有效期（秒）',
		name: 'chat_expires_in',
		type: 'number',
		default: 0,
		displayOptions: { show: showOnly },
		description: '临时会话有效期，以秒为单位。仅在临时会话模式下有效',
	},
	{
		displayName: '客户UnionID',
		name: 'unionid',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		description: '可进行临时会话的客户unionid，仅在临时会话模式有效，如不指定则不进行限制',
		placeholder: 'oxTWIuGaIt6gTKsQRLau2M0AAAA',
	},
	{
		displayName: '标记客户来源',
		name: 'mark_source',
		type: 'boolean',
		default: true,
		displayOptions: { show: showOnly },
		description: '是否标记客户添加来源为该应用创建的「联系我」，仅对「营销获客」应用生效，且只能由创建此「联系我」的应用进行更新',
	},
	{
		displayName: '设置结束语',
		name: 'enableConclusions',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否设置结束语，会话结束时自动发送给客户，仅临时会话模式（is_temp为true）可设置',
	},
	{
		displayName: '结束语类型',
		name: 'conclusionType',
		type: 'options',
		displayOptions: { show: { ...showOnly, enableConclusions: [true] } },
		options: [
			{ name: '文本', value: 'text' },
			{ name: '图片', value: 'image' },
			{ name: '链接', value: 'link' },
			{ name: '小程序', value: 'miniprogram' },
		],
		default: 'text',
		description: '结束语消息类型',
	},
	{
		displayName: '文本内容',
		name: 'conclusion_text',
		type: 'string',
		typeOptions: { rows: 3 },
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['text'] } },
		default: '',
		description: '消息文本内容，最长为4000字节',
		placeholder: '感谢您的咨询',
	},
	{
		displayName: '图片Media ID',
		name: 'conclusion_image_media_id',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['image'] } },
		default: '',
		description: '图片的media_id',
	},
	{
		displayName: '链接标题',
		name: 'conclusion_link_title',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['link'] } },
		default: '',
		description: '图文消息标题，最长为128字节',
	},
	{
		displayName: '链接封面URL',
		name: 'conclusion_link_picurl',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['link'] } },
		default: '',
		description: '图文消息封面的URL',
	},
	{
		displayName: '链接描述',
		name: 'conclusion_link_desc',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['link'] } },
		default: '',
		description: '图文消息的描述，最长为512字节',
	},
	{
		displayName: '链接URL',
		name: 'conclusion_link_url',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['link'] } },
		default: '',
		description: '图文消息的链接',
	},
	{
		displayName: '小程序标题',
		name: 'conclusion_miniprogram_title',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['miniprogram'] } },
		default: '',
		description: '小程序消息标题，最长为64字节',
	},
	{
		displayName: '小程序AppID',
		name: 'conclusion_miniprogram_appid',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['miniprogram'] } },
		default: '',
		description: '小程序appid，必须是关联到企业的小程序应用',
	},
	{
		displayName: '小程序页面路径',
		name: 'conclusion_miniprogram_page',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['miniprogram'] } },
		default: '',
		description: '小程序page路径',
		placeholder: '/path/index',
	},
	{
		displayName: '小程序封面Media ID',
		name: 'conclusion_miniprogram_pic_media_id',
		type: 'string',
		displayOptions: { show: { ...showOnly, enableConclusions: [true], conclusionType: ['miniprogram'] } },
		default: '',
		description: '小程序消息封面的mediaid，封面图建议尺寸为520*416',
	},
];
