import type { INodeProperties } from 'n8n-workflow';

const showOnly = {
	resource: ['externalContact'],
	operation: ['updateInterceptRule'],
};

export const updateInterceptRuleDescription: INodeProperties[] = [
	{
		displayName: '规则ID（必填）',
		name: 'rule_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: showOnly },
		description: '规则ID',
	},
	{
		displayName: '规则名称',
		name: 'rule_name',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		description: '规则名称，长度1~20个utf8字符。不需更新的字段可不填',
	},
	{
		displayName: '敏感词列表',
		name: 'word_list',
		type: 'string',
		default: '',
		displayOptions: { show: showOnly },
		typeOptions: { rows: 3 },
		description: '敏感词列表，多个敏感词用逗号分隔。若为空则忽略该字段',
		placeholder: '敏感词1,敏感词2',
	},
	{
		displayName: '更新拦截方式',
		name: 'updateInterceptType',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否更新拦截方式',
	},
	{
		displayName: '拦截方式',
		name: 'intercept_type',
		type: 'options',
		options: [
			{ name: '警告并拦截发送', value: 1 },
			{ name: '仅发警告', value: 2 },
		],
		default: 1,
		displayOptions: { show: { ...showOnly, updateInterceptType: [true] } },
	},
	// 更新语义规则
	{
		displayName: '更新拦截语义规则',
		name: 'updateSemantics',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否更新额外的拦截语义规则。若设置为空列表表示清除所有的语义规则',
	},
	{
		displayName: '额外拦截语义规则',
		name: 'semantics_list',
		type: 'multiOptions',
		options: [
			{ name: '手机号', value: 1 },
			{ name: '邮箱地址', value: 2 },
			{ name: '红包', value: 3 },
		],
		default: [],
		displayOptions: { show: { ...showOnly, updateSemantics: [true] } },
		description: '额外的拦截语义规则，若为空表示清除所有的语义规则',
	},
	// 新增适用范围
	{
		displayName: '新增适用范围',
		name: 'enableAddRange',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否新增使用范围',
	},
	{
		displayName: '新增成员UserID列表',
		name: 'add_user_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, enableAddRange: [true] } },
		description: '需要新增的userid列表，用逗号分隔。每次最多支持传1000个节点；该规则最多可包含的userid总数上限为10000个',
		placeholder: 'zhangsan,lisi',
	},
	{
		displayName: '新增部门ID列表',
		name: 'add_department_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, enableAddRange: [true] } },
		description: '需要新增的部门ID列表，用逗号分隔。最多支持传1000个节点',
		placeholder: '1,2,3',
	},
	// 删除适用范围
	{
		displayName: '删除适用范围',
		name: 'enableRemoveRange',
		type: 'boolean',
		default: false,
		displayOptions: { show: showOnly },
		description: '是否删除使用范围',
	},
	{
		displayName: '删除成员UserID列表',
		name: 'remove_user_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, enableRemoveRange: [true] } },
		description: '需要删除的userid列表，用逗号分隔。最多支持传1000个节点',
		placeholder: 'zhangsan,lisi',
	},
	{
		displayName: '删除部门ID列表',
		name: 'remove_department_list',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showOnly, enableRemoveRange: [true] } },
		description: '需要删除的部门ID列表，用逗号分隔。最多支持传1000个节点',
		placeholder: '1,2,3',
	},
];
