import type { INodeProperties } from 'n8n-workflow';

const showOnly = { resource: ['meetingroom'], operation: ['manageMeetingroom'] };

export const manageMeetingroomDescription: INodeProperties[] = [
	{
		displayName: '操作类型',
		name: 'action',
		type: 'options',
		required: true,
		displayOptions: { show: showOnly },
		options: [
			{ name: '查询会议室列表', value: 'list' },
			{ name: '查询会议室', value: 'get' },
			{ name: '添加会议室', value: 'add' },
			{ name: '编辑会议室', value: 'edit' },
			{ name: '删除会议室', value: 'delete' },
		],
		default: 'list',
		description: '选择对会议室进行的管理操作',
	},
	// 查询会议室列表参数
	{
		displayName: '城市',
		name: 'city',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['list'] } },
		default: '',
		description: '按城市筛选会议室',
		hint: '城市名称（可选）',
	},
	{
		displayName: '楼宇',
		name: 'building',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['list'] } },
		default: '',
		description: '按楼宇筛选会议室',
		hint: '楼宇名称（可选）',
	},
	{
		displayName: '楼层',
		name: 'floor',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['list'] } },
		default: '',
		description: '按楼层筛选会议室',
		hint: '楼层名称（可选）',
	},
	{
		displayName: '设备类型',
		name: 'equipment',
		type: 'multiOptions',
		displayOptions: { show: { ...showOnly, action: ['list'] } },
		options: [
			{ name: '电视', value: 1 },
			{ name: '电话', value: 2 },
			{ name: '投影', value: 3 },
			{ name: '白板', value: 4 },
			{ name: '视频', value: 5 },
		],
		default: [],
		description: '按设备类型筛选会议室',
	},
	// 查询单个会议室参数
	{
		displayName: '会议室ID',
		name: 'meetingroom_id',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['get', 'edit', 'delete'] } },
		default: '',
		description: '会议室的唯一标识ID',
		hint: '会议室ID',
	},
	// 添加/编辑会议室参数
	{
		displayName: '会议室名称',
		name: 'name',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['add'] } },
		default: '',
		description: '会议室的名称',
		hint: '会议室名称',
	},
	{
		displayName: '会议室名称',
		name: 'name_edit',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['edit'] } },
		default: '',
		description: '新的会议室名称，留空则不修改',
		hint: '新会议室名称（可选）',
	},
	{
		displayName: '容纳人数',
		name: 'capacity',
		type: 'number',
		required: true,
		displayOptions: { show: { ...showOnly, action: ['add'] } },
		default: 10,
		description: '会议室可容纳的人数',
		typeOptions: { minValue: 1 },
	},
	{
		displayName: '容纳人数',
		name: 'capacity_edit',
		type: 'number',
		displayOptions: { show: { ...showOnly, action: ['edit'] } },
		default: 0,
		description: '新的容纳人数，0表示不修改',
		typeOptions: { minValue: 0 },
	},
	{
		displayName: '所在城市',
		name: 'city_add',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['add', 'edit'] } },
		default: '',
		description: '会议室所在城市',
		hint: '城市（可选）',
	},
	{
		displayName: '所在楼宇',
		name: 'building_add',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['add', 'edit'] } },
		default: '',
		description: '会议室所在楼宇',
		hint: '楼宇（可选）',
	},
	{
		displayName: '所在楼层',
		name: 'floor_add',
		type: 'string',
		displayOptions: { show: { ...showOnly, action: ['add', 'edit'] } },
		default: '',
		description: '会议室所在楼层',
		hint: '楼层（可选）',
	},
	{
		displayName: '设备类型',
		name: 'equipment_add',
		type: 'multiOptions',
		displayOptions: { show: { ...showOnly, action: ['add', 'edit'] } },
		options: [
			{ name: '电视', value: 1 },
			{ name: '电话', value: 2 },
			{ name: '投影', value: 3 },
			{ name: '白板', value: 4 },
			{ name: '视频', value: 5 },
		],
		default: [],
		description: '会议室配备的设备类型',
	},
];
